DjangoShop-master/second_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from shop import views as shop_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', shop_views.index, name = 'root'),
    url(r'^shop/', include('shop.urls')),
    url(r'^accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoShop-master/shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile/(?P<pk>[0-9]+)/order_list/$', views.order_list, name='order_list'),
    url(r'^notice/$', views.notice, name='notice'),
    url(r'^notice/(?P<pk>[0-9]+)/$', views.notice_detail, name='notice_detail'),
    url(r'^(?P<category_id>[0-9]+)/$', views.show_category, name='show_category'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.product_detail, name='product_detail'),
    url(r'^(?P<pk>[0-9]+)/cart_or_buy$', views.cart_or_buy, name='cart_or_buy'),
    url(r'^cart/(?P<pk>[0-9]+)/$', views.cart, name='cart'),
    url(r'^cart/(?P<pk>[0-9]+)/delete', views.delete_cart, name='delete_cart'),

]

DjangoShop-master/shop/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User, AbstractUser
from sorl.thumbnail import ImageField

class Category(models.Model):
    sort = models.CharField(max_length=255)

    def __str__(self):
        return '{}'.format(self.sort)


class Product(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product_category')
    image = ImageField(upload_to='photos')
    price = models.IntegerField()
    quantity = models.IntegerField(default=0)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add = True)
    hit = models.IntegerField(default=0)

    def __str__(self):
        return '{} {}'.format(self.name, self.pub_date)


class Point(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,)
    all_point = models.IntegerField()
    able_point = models.IntegerField()


class Cart(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, )
    products = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='wish_product', blank=True)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return '{} // {}'.format(self.user, self.products.name)

class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} by {}'.format(self.title, self.author)


class Order(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, )
    name = models.CharField(max_length=100, verbose_name='상품명')
    amount = models.PositiveIntegerField(verbose_name='결제금액')
    quantity = models.IntegerField(default=1)
    products = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_product')
    order_date = models.DateTimeField(auto_now_add=True)

    #모델 인스턴스를 아이디 값 내림차순 정렬
    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return '{} by {}'.format(self.products.name, self.user)

DjangoShop-master/shop/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'amount', 'quantity']
        widgets = {
            'name': forms.TextInput(attrs={'readonly': 'readonly'}),
            'amount': forms.TextInput(attrs={'readonly': 'readonly'}),
            'quantity': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

DjangoShop-master/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.db.models import F
from .models import Product, Post, Point, Order, Category, Cart
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import OrderForm
# Create your views here.


def index(request):
    products = Product.objects.order_by('-pub_date')
    categories = Category.objects.all()
    context = {'products': products, 'categories': categories}

    return render(request, 'shop/index.html', context)



def profile(request, pk):
    user = User.objects.get(pk=pk)
    categories = Category.objects.all()
    return render(request, 'shop/profile.html', {'categories': categories})


def notice(request):
    post_list = Post.objects.all()
    categories = Category.objects.all()
    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'posts': posts, 'categories': categories}
    return render(request, 'shop/notice.html', context)


def notice_detail(request, pk):
    categories = Category.objects.all()
    post = Post.objects.get(pk=pk)
    context = {"post": post, "categories":  categories}
    return render(request, 'shop/notice_detail.html', context)



def order_list(request, pk):
    categories = Category.objects.all()
    user = User.objects.get(pk=pk)
    orders = Order.objects.filter(user=user)
    paginator = Paginator(orders, 5)
    page = request.GET.get('page')
    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)
    context = {'user': user, 'orders': orders, 'categories': categories}
    return render(request, 'shop/order_list.html', context)


def show_category(request, category_id):
    categories = Category.objects.all()
    category = Category.objects.get(pk=category_id)
    products = Product.objects.filter(category=category).order_by('pub_date')
    lank_products = Product.objects.filter(category=category).order_by('-hit')[:4]
    paginator = Paginator(products, 5)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    context = {'lank_products': lank_products, 'products': products, 'category': category, 'categories': categories}
    return render(request, 'shop/category.html', context)


def product_detail(request, pk):
    categories = Category.objects.all()
    product = Product.objects.get(pk=pk)
    category = Category.objects.get(pk=product.category.pk)
    Product.objects.filter(pk=pk).update(hit=product.hit+1)
    point = int(product.price * 0.01)
    quantity_list = []
    for i in range(1, product.quantity) :
        quantity_list.append(i)
    context = {"quantity_list": quantity_list, "product": product, "point": point, "category": category, "categories": categories}
    return render(request, 'shop/detail.html', context)


def cart(request, pk):
    categories = Category.objects.all()
    user = User.objects.get(pk=pk)
    cart = Cart.objects.filter(user=user)
    paginator = Paginator(cart, 10)
    page = request.GET.get('page')
    try:
        cart = paginator.page(page)
    except PageNotAnInteger:
        cart = paginator.page(1)
    except EmptyPage:
        cart = paginator.page(paginator.num_pages)
    context = {'user': user, 'cart': cart, 'categories': categories}
    return render(request, 'shop/cart.html', context)

def delete_cart(request, pk):
    user = request.user
    cart = Cart.objects.filter(user=user)
    quantity = 0

    if request.method == 'POST':
        pk = int(request.POST.get('product'))
        product = Product.objects.get(pk=pk)
        for i in cart:
            if i.products == product :
                quantity =  i.quantity

        if quantity > 0 :
            product = Product.objects.filter(pk=pk)
            cart = Cart.objects.filter(user=user, products__in=product)
            cart.delete()
            return redirect('shop:cart', user.pk)

@login_required
def cart_or_buy(request, pk):
    quantity = int(request.POST.get('quantity'))
    product = Product.objects.get(pk=pk)
    user = request.user
    categories = Category.objects.all()
    initial = {'name': product.name, 'amount': product.price, 'quantity': quantity}
    cart = Cart.objects.filter(user=user)
    if request.method == 'POST':
        if 'add_cart' in request.POST:
            for i in cart :
                if i.products == product:
                    product = Product.objects.filter(pk=pk)
                    Cart.objects.filter(user=user, products__in=product).update(quantity=F('quantity') + quantity)
                    messages.success(request,'장바구니 등록 완료')
                    return redirect('shop:cart', user.pk)

            Cart.objects.create(user=user, products=product, quantity=quantity)
            messages.success(request, '장바구니 등록 완료')
            return redirect('shop:cart', user.pk)

        elif 'buy' in request.POST:
            form = OrderForm(request.POST, initial=initial)
            if form.is_valid():
                order = form.save(commit=False)
                order.user = user
                order.quantity = quantity
                order.products = product
                order.save()
                return redirect('shop:order_list', user.pk)

            else:
                form = OrderForm(initial=initial)

            return render(request, 'shop/order_pay.html', {
                'form': form,
                'quantity': quantity,
                'iamport_shop_id': 'iamport',  # FIXME: 가맹점코드
                'user': user,
                'product': product,
                'categories': categories,
            })

DjangoShop-master/shop/templates/shop/cart.html
{% extends "shop/../account/base.html" %}

{% block title %}
    MY CART
{% endblock title %}

{% block content %}
    {% load staticfiles %}
    {% load thumbnail %}
    <link rel="stylesheet" type='text/css' href="{% static 'shop/style.css' %}">
    <div class="content">
        <div id="pagetitle">
            <h3>SHOPPING CART</h3>
        </div>
        <form action="{% url "shop:delete_cart" user.pk %}" method="POST">
            <div class="order_list">
                <table>
                    <thead>
                    <tr>
                        <th class="thumb">
                            SELECT
                        </th>
                        <th class="thumb">
                            IMAGE
                        </th>
                        <th class="product">
                            PRODUCT
                        </th>
                        <th class="quantity">
                            QUANTITY
                        </th>
                        <th class="price">
                            PRICE
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <!-- 리스트 안에 담겨서 나오기 때문에 for 문을 써서 출력 -->
                    {% for product in cart %}
                        <tr>
                            <td>
                                <input type="radio" id="product_{{ product.id }}" name="product" value="{{ product.products.id }}">
                            </td>
                            <td class="thumb">
                                {% thumbnail product.products.image "100x100" crop="center" as im %}
                                    <a href="{% url 'shop:product_detail' product.products.pk %}">
                                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ product.name }}">
                                    </a>
                                {% endthumbnail %}
                            </td>
                            <td class="product">
                                {{ product.products.name }}
                            </td>
                            <td class="quantity">
                                {{ product.quantity }}
                            </td>
                            <td>
                                {{ product.products.price }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>

            <div class="order_option">
            <span class="left">
                <span class="text">
                    선택상품을
                </span>
                <button type="submit" name="delete_cart" value="delete_cart">삭제하기</button>
                {% csrf_token %}
            </span>
            </div>
        </form>
        <!-- pagenation nav -->
        <div class="board_paging">
            <ol>
                {% if orders.has_previous %}
                    <li class="paging_pre">
                        <a href="{% url 'shop:order_list' %}?page={{ orders.previous_page_number }}"><</a>
                    </li>
                {% endif %}

                <li><a href="#">{{ orders.number }}</a></li>

                {% if orders.has_next %}
                    <li class="paging_next">
                        <a href="{% url 'shop:orser_list' %}?page={{ orders.next_page_number }}">></a>
                    </li>
                {% endif %}
            </ol>
        </div>
    </div>
{% endblock content %}

DjangoShop-master/shop/templates/shop/category.html
{% extends "shop/../account/base.html" %}

{% block title %}
    {{ category }}
{% endblock title %}

{% block content %}
    {% load staticfiles %}
    {% load thumbnail %}
    <link rel="stylesheet" type='text/css' href="{% static 'shop/style.css' %}">
    <div class="content">
        <div class="product_title">
            <h2>
                <span>{{ category }}</span>
            </h2>
        </div>
        <div class="recommend_list">
            <ul class="product_list">
                {% for product in lank_products %}
                    <li>
                        <div class="box">
                            <h3>
                                <span>BEST</span>
                            </h3>
                            {% thumbnail product.image "240x240" crop="center" as im %}
                                <a href="{% url 'shop:product_detail' product.pk %}">
                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ product.name }}">
                                </a>
                            {% endthumbnail %}
                            <p class="name">
                                <a href="{% url 'shop:product_detail' product.pk %}">
                                    <strong class="displaynone">
                                        <span style="font-size: 11px; color:#222222;">{{ product.products.name }}</span>
                                    </strong>
                                </a>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="nomal_list">
            <ul class="product_list">
                {% for product in products %}
                    <li>
                        <div class="box">
                            {% thumbnail product.image "240x240" crop="center" as im %}
                                <a href="{% url 'shop:product_detail' product.pk %}">
                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ product.name }}">
                                </a>
                            {% endthumbnail %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <!-- pagenation nav -->
        <div class="board_paging">
            <ol>
                {% if products.has_previous %}
                    <li class="paging_pre">
                        <a href="{% url 'shop:show_products' %}?page={{ products.previous_page_number }}"><</a>
                    </li>
                {% endif %}

                <li><a href="#">{{ products.number }}</a></li>

                {% if products.has_next %}
                    <li class="paging_next">
                        <a href="{% url 'shop:show_products' %}?page={{ products.next_page_number }}">></a>
                    </li>
                {% endif %}
            </ol>
        </div>
    </div>
{% endblock content %}

DjangoShop-master/shop/templates/shop/detail.html
{% extends "shop/../account/base.html" %}

{% block title %}
    DETAIL
{% endblock title %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type='text/css' href="{% static 'shop/style.css' %}">
    <div class="content">
        <div class="detailArea">
            <div class="product_img_area">
                <div class="key_img">
                    <img src = '{{ product.image.url }}' width='300' />
                </div>
            </div>
            <div class="infoArea">
                <h3>{{ product.name }}</h3>
                <div class="detailinfo">
                    <p>{{ product.description }}</p>
                </div>
            <form action="{% url "shop:cart_or_buy" product.pk %}", method="POST">
                <div class="detail_payment">
                    <table>
                        <tbody>
                        <tr>
                            <th>
                                <span>
                                    PRICE
                                </span>
                            </th>
                            <td>
                                <span>
                                    <strong>
                                        {{ product.price }} 원
                                    </strong>
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <span>
                                    POINT
                                </span>
                            </th>
                            <td>
                                <span>
                                    <strong>
                                        {{ point }} 원
                                    </strong>
                                </span>
                            </td>
                        </tr>
                        </tbody>
                    </table>

                        {% if product.quantity > 0 %}
                            <table>
                                <tbody class="product_option">
                                <tr class="product_quantity">
                                    <th>
                                        수량
                                    </th>
                                    <td>
                                        <select name="quantity">
                                            {% for quantity in quantity_list %}
                                                <option value={{ quantity }}>{{ quantity }}</option>
                                            {% endfor %}
                                        </select>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        {% else %}
                            <table>
                                <tbody class="product_option">
                                <tr class="product_quantity">
                                    <th>
                                        SOLD OUT
                                    </th>
                                </tr>
                                </tbody>
                            </table>
                        {% endif %}
                </div>

                <div class="payment">
                    <div class="btnArea">
                        <ul>
                            {% if product.quantity > 0 %}
                                <li class="cart">
                                    <button type="submit" name="add_cart" value="add_cart">+ ADD SHOPPING CART</button>
                                    {% csrf_token %}
                                </li>
                                <li class="buy">
                                    <button type="submit" name="buy" value="buy_it_now">BUY IT NOW</button>
                                    {% csrf_token %}
                                </li>
                                {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                            <li class="{{ message.tags }}">
                                                {{ message }}<br>
                                                <a href="{% url "shop:cart" user.pk %}">장바구니로 이동</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            {% else %}
                                <li class="soldout">
                                    SOLD OUT (X)
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                </form>
            </div>
        </div>


    </div>
{% endblock content %}

DjangoShop-master/shop/templates/shop/index.html
{% extends "shop/../account/base.html" %}

{% block title %}
    Index
{% endblock title %}

{% block content %}

            {% block right_side %} {% include 'shop/right_side.html' %} {% endblock right_side %}

{% endblock content %}

DjangoShop-master/shop/templates/shop/left_side.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'shop/style.css' %}" type="text/css">

<div class="logo-space">
    <a href="{% url 'root' %}"><img src="{% static 'shop/images/main.png' %}"></a>
</div>

<div class="side-top">
    <div class="account">
        <ul>
            {% if user.is_active %}
                <li>
                    <a href="{% url 'account_logout' %}">LOGOUT</a>
                </li>
                <li>
                    <a href="{% url 'shop:profile' user.pk %}">MY PAGE</a>
                </li>
                <li>
                    <a href="{% url 'shop:cart' user.pk %}">CART</a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'account_login' %}">LOGIN</a>
                </li>
                <li>
                    <a href="{% url 'account_signup' %}">SIGN UP</a>
                </li>
            {% endif %}
        </ul>
    </div>

    <ul>
        <li>
            <a href="{% url 'shop:notice' %}">NOTICE</a>
        </li>
        <li>
            <a href="...">Q&A</a>
        </li>
        <li>
            <a href="...">REVIEW</a>
        </li>
        <li>
            <a href="...">MEMBERSHIP</a>
        </li>
        <li>
            <a href="...">입고지연</a>
        </li>
    </ul>
</div>

<div class="side-category">
    <ul>
        {% for category in categories %}
            <li>
                <a href="{% url 'shop:show_category' category.pk %}">{{ category.sort }}</a>
            </li>
        {% endfor %}
        <li>
            <a href="...">SALE</a>
        </li>
    </ul>
</div>

<div class="side-bottom">
    <ul>
        <li>
            C/S CENTER. 031-XXX-XXXX
        </li>
        <li>
            MON-FRI / 11:00 - 18:00
        </li>
        <li>
            LUNCH 12:00 - 13:00
        </li>
        <li>
            SAT, SUN, HOLLIDAY OFF
        </li>
        <li>
            BANKING.
        </li>
        <li>
            신한 XXX-XXX-XXXXXX
        </li>
        <li>
            국민 XXXXXX-XX-XXXXXX
        </li>
        <li>
            [이종진(쇼핑몰)]
        </li>
    </ul>
</div>

DjangoShop-master/shop/templates/shop/notice.html
{% extends "shop/../account/base.html" %}

{% block title %}
    NOTICE
{% endblock title %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type='text/css' href="{% static 'shop/style.css' %}">
    <div class="content">
        <div id="board_list">
            <div id="board_list_title">
                <div id="board_title">
                    <h2>
                        <span>NOTICE</span>
                    </h2>
                </div>
            </div>

            <div class="board_table">
                <table>
                    <thead>
                    <tr>
                        <th>no</th>
                        <th>제목</th>
                        <th>작성자</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for post in posts %}
                        <tr>
                            <td>{{ post.id }}</td>
                            <td><a href="{% url 'shop:notice_detail' post.pk %}">{{ post.title }}</a></td>
                            <td>{{ post.author }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- pagenation nav -->
        <div class="board_paging">
            <ol>
            {% if posts.has_previous %}
                <li class="paging_pre">
                    <a href="{% url 'shop:notice' %}?page={{ posts.previous_page_number }}"><</a>
                </li>
            {% endif %}

                <li><a href="#">{{ posts.number }}</a></li>

            {% if posts.has_next %}
                <li class="paging_next">
                    <a href="{% url 'shop:notice' %}?page={{ posts.next_page_number }}">></a>
                </li>
            {% endif %}
            </ol>
        </div>
    </div>
{% endblock content %}

DjangoShop-master/shop/templates/shop/notice_detail.html
{% extends "shop/../account/base.html" %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type='text/css' href="{% static 'shop/style.css' %}">
    <div class="content">
        <div id="board_list">
            <div id="board_list_title">
                <div id="board_title">
                    <h2>
                        <span>NOTICE</span>
                    </h2>
                </div>
            </div>
        </div>
    <div class="board_view">
        <table>
            <tbody>
            <tr>
                <td>{{ post.title }}</td>
            </tr>
            <tr>
                <td>
                    <p>
                        {{ post.content }}
                    </p>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="board_bottom">
        <span class="left">
            <a href="{% url 'shop:notice' %}">LIST</a>
        </span>
    </div>
    </div>
{% endblock content %}

DjangoShop-master/shop/templates/shop/order_pay.html
{% extends "shop/../account/base.html" %}

{% block title %}
    PAYMENT
{% endblock title %}

{% block content %}
    {% load staticfiles %}
    {% load thumbnail %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js" ></script>
    <script type="text/javascript" src="https://service.iamport.kr/js/iamport.payment-x.y.z.js"></script>

    <link rel="stylesheet" type='text/css' href="{% static 'shop/style.css' %}">
    <div class="content">
        <div id="pagetitle">
            <h3>PAYMENT</h3>
        </div>
        <div class="order_list">
            <table>
                <thead>
                <tr>
                    <th class="thumb">
                        IMAGE
                    </th>
                    <th class="product">
                        PRODUCT
                    </th>
                    <th class="quantity">
                        QUANTITY
                    </th>
                    <th class="price">
                        PRICE
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="thumb">
                        {% thumbnail product.image "100x100" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ im.name }}">
                        {% endthumbnail %}
                    </td>
                    <td class="product">
                        {{ product.name }}
                    </td>
                    <td class="quantity">
                        {{ quantity }}
                    </td>
                    <td>
                        {{ product.price }}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="order_option">
            <form action="" method="POST" id="order-form">
                {% csrf_token %}
                <div>
                    <table>
                        {{ form.as_table }}
                    </table>
                    {{ initial }}
                </div>
                <input type="submit" class="btn" value="결제하기">
            </form>
        </div>
    </div>
{% endblock content %}

{% block extra_body %}
    <script src="https://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
    <script>
        $(function() {
            var $form = $('#order-form');
            var params = {
                name: $form.find('[name=name]').val(),
                amount: $form.find('[name=amount]').val(),
            };
            IMP.init('{{ iamport_shop_id }}');
            IMP.request_pay(params, function(response_data) {
                console.log('response_data :', response_data);
                if ( ! response_data.success ) {
                    alert(response_data.error_msg + "(" + response_data.error_code + ")");
                    location.href = '{% url "shop:index" %}';
                }
                else {
                     $.each(response_data, function(key, vlaue) {
                        $form.find("input[name=" + key + "]").val(value);
                    });
                    $form.submit();
                }
            });
        });
    </script>

{% endblock %}

DjangoShop-master/shop/templates/shop/sale.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>